#!/usr/bin/env python3
"""Build the frozen LookAway token priors.

Usage:
    python scripts/prepare_priors.py --data-dir ./cache/lookaway \
        --model-path Qwen/Qwen3.5-4B \
        --model-revision 851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a \
        [--device cuda:0] [--limit N]

Stage 1 - three-view token dump: the base model greedily answers every
training question from the student view (red-box full image); the same answer
is re-scored under the positive teacher view (official crop) and the negative
teacher view (generated by prepare_data.py). Per-token log-probabilities are
stored, together with the per-token deltas d_plus = lp_pos - lp_student and
d_minus = lp_neg - lp_student.

Stage 2 - priors derived from the dump (token-id keyed):
  * word selection rate: empirical-Bayes smoothed rate at which each token
    passes the dual-signal top-decile selection; used as an eligibility gate
    (function words score far below the 0.12 cut, content words above it);
  * template bigrams: contextual bigrams whose document frequency across the
    corpus reaches 0.25; used to reject pointing boilerplate.

Output: {data_dir}/token_priors.json  (keys: rate / tmpl / meta)
"""

import argparse
import hashlib
import json
import os
from collections import defaultdict

import numpy as np
import torch
from PIL import Image
from transformers import AutoModelForImageTextToText, AutoProcessor, AutoTokenizer

ALPHA, BASE = 50.0, 0.10  # empirical-Bayes pseudo-counts
BATCH = 16
TMPL_DF_CUT = 0.25
MAX_NEW_TOKENS = 96
DEFAULT_MODEL_REVISION = "851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a"
DEFAULT_MODEL_PATH = "Qwen/Qwen3.5-4B"
DEFAULT_CHAT_TEMPLATE = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "chat_templates",
    "perception_chat_template_qwen35.jinja",
)


def parse_args():
    ap = argparse.ArgumentParser(description="Build frozen LookAway token priors.")
    ap.add_argument("--data-dir", default="./cache/lookaway")
    ap.add_argument("--model-path", default=DEFAULT_MODEL_PATH)
    ap.add_argument(
        "--model-revision",
        default=None,
        help="Pinned Hugging Face model revision (required for non-default remote models)",
    )
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--limit", type=int, default=0, help=">0: use only the first N samples (smoke test)")
    ap.add_argument(
        "--chat-template",
        default=DEFAULT_CHAT_TEMPLATE,
        help="Path to the training chat template (defaults to the repository's Qwen3.5 template)",
    )
    return ap.parse_args()


def generated_answer_ids(generated_ids, tokenizer):
    """Keep rollout token IDs while trimming terminal generation-control tokens."""
    token_ids = generated_ids.tolist() if hasattr(generated_ids, "tolist") else list(generated_ids)
    special_ids = set(tokenizer.all_special_ids)
    while token_ids and int(token_ids[-1]) in special_ids:
        token_ids.pop()
    return [int(token_id) for token_id in token_ids]


def file_sha256(path):
    value = hashlib.sha256()
    with open(path, "rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            value.update(block)
    return value.hexdigest()


def tokenizer_fingerprint(tokenizer):
    """Hash the token-ID mapping and special tokens used by token-keyed priors."""
    payload = {
        "vocab": sorted((str(token), int(token_id)) for token, token_id in tokenizer.get_vocab().items()),
        "special_tokens_map": {key: str(value) for key, value in sorted(tokenizer.special_tokens_map.items())},
    }
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def find_answer_start(input_ids, answer_ids, search_window=16):
    """Locate the assistant answer near the end of a templated sequence."""
    if not answer_ids:
        raise ValueError("Cannot score an empty generated answer.")
    first_start = max(0, len(input_ids) - len(answer_ids) - search_window)
    for start in range(len(input_ids) - len(answer_ids), first_start - 1, -1):
        if input_ids[start : start + len(answer_ids)] == answer_ids:
            return start
    raise ValueError("Generated answer token IDs were not found in the templated scoring input.")


def build_inputs(proc, img_path, question, answer_ids=None, device="cuda", chat_template=None):
    content = [
        {"type": "image", "image": img_path},
        {"type": "text", "text": question.replace("<image>", "", 1)},
    ]
    msgs = [{"role": "user", "content": content}]
    kwargs = {}
    if chat_template is not None:
        with open(chat_template, encoding="utf-8") as f:
            kwargs["chat_template"] = f.read()
    text = proc.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True, enable_thinking=False, **kwargs)
    img = Image.open(img_path).convert("RGB")
    inputs = proc(text=[text], images=[img], return_tensors="pt").to(device)
    if answer_ids is not None:
        prompt_length = inputs["input_ids"].shape[1]
        answer_tensor = torch.tensor(answer_ids, dtype=inputs["input_ids"].dtype, device=device).unsqueeze(0)
        inputs["input_ids"] = torch.cat([inputs["input_ids"], answer_tensor], dim=1)
        answer_mask = torch.ones_like(answer_tensor, dtype=inputs["attention_mask"].dtype)
        inputs["attention_mask"] = torch.cat([inputs["attention_mask"], answer_mask], dim=1)
        for key in ("token_type_ids", "mm_token_type_ids"):
            value = inputs.get(key)
            if value is not None and value.ndim == 2 and value.shape[1] == prompt_length:
                answer_types = torch.zeros_like(answer_tensor, dtype=value.dtype)
                inputs[key] = torch.cat([value, answer_types], dim=1)
    return inputs


def run_dump(args, tok, proc, model):
    """Stage 1: three-view greedy scoring dump from a complete aligned dataset."""
    out_path = os.path.join(args.data_dir, "token_scores_full.jsonl")
    with open(os.path.join(args.data_dir, "train.jsonl"), encoding="utf-8") as f:
        all_rows = [json.loads(line) for line in f]

    results_path = os.path.join(args.data_dir, "results.json")
    if not os.path.exists(results_path):
        raise FileNotFoundError("results.json is required; run scripts/prepare_data.py first")
    with open(results_path, encoding="utf-8") as f:
        generation_results = json.load(f)
    expected_ids = list(range(len(all_rows)))
    actual_ids = [record.get("idx") for record in generation_results]
    if actual_ids != expected_ids or not all(
        record.get("ok") and record.get("generation_version") == "2.0.0" for record in generation_results
    ):
        raise ValueError("results.json is incomplete or was not generated by the aligned v2 pipeline")
    rows = all_rows[: args.limit] if args.limit > 0 else all_rows
    total = len(rows)

    tpl = args.chat_template
    n_written = 0
    with open(out_path, "w", encoding="utf-8") as fout:
        for i, h in enumerate(rows):
            q = h["problem"]

            # 1) greedy student rollout
            inputs = build_inputs(
                proc,
                os.path.join(args.data_dir, h["images"][0]),
                q,
                device=args.device,
                chat_template=tpl,
            )
            with torch.no_grad():
                out = model.generate(
                    **inputs, max_new_tokens=MAX_NEW_TOKENS, do_sample=False, pad_token_id=tok.eos_token_id
                )
            gen_ids = out[0][inputs["input_ids"].shape[1] :]
            ans_ids = generated_answer_ids(gen_ids, tok)
            if not ans_ids:
                print(f"Skipping row {i}: model generated no content tokens.")
                continue
            answer = tok.decode(ans_ids, skip_special_tokens=False)
            K = len(ans_ids)

            # 2) three-view scoring
            lps = {}
            views = {
                "student": os.path.join(args.data_dir, h["images"][0]),
                "pos": os.path.join(args.data_dir, h["teacher_images"][0]),
                "neg": os.path.join(args.data_dir, "teacher_neg", f"{i:06d}.png"),
            }
            for tag, img_path in views.items():
                inputs = build_inputs(proc, img_path, q, ans_ids, device=args.device, chat_template=tpl)
                with torch.no_grad():
                    logits = model(**inputs).logits[0]
                lp = torch.log_softmax(logits.float(), dim=-1)
                ids = inputs["input_ids"][0]
                idl = ids.tolist()
                try:
                    pos_ans = find_answer_start(idl, ans_ids)
                except ValueError as exc:
                    raise ValueError(f"Unable to align answer tokens for row {i}, view {tag}.") from exc
                vals = []
                for j in range(K):
                    t_pos = pos_ans + j
                    vals.append(lp[t_pos - 1, idl[t_pos]].item())
                lps[tag] = vals

            # 3) per-token deltas (relative to the student score)
            rec = {
                "n": n_written,
                "idx": i,
                "gt": h.get("answer", ""),
                "answer": answer,
                "question": q[:100],
                "tokens": [],
            }
            toks = tok.convert_ids_to_tokens(ans_ids)
            for j, token in enumerate(toks):
                student_lp = lps["student"][j]
                rec["tokens"].append(
                    {
                        "tok": token,
                        "lp_s": round(student_lp, 4),
                        "d_plus": round(lps["pos"][j] - student_lp, 4),
                        "d_minus": round(lps["neg"][j] - student_lp, 4),
                    }
                )
            fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
            fout.flush()
            n_written += 1
            if n_written % 100 == 0:
                print(f"dump [{n_written}/{total}]", flush=True)
    print(f"Token dump written: {out_path}")
    return out_path


def run_priors(args, dump_path, tok):
    """Stage 2: frozen priors from the dump."""
    recs = []
    with open(dump_path, encoding="utf-8", errors="ignore") as f:
        for line in f:
            record = json.loads(line)
            recs.append(
                [
                    (str(token["tok"]), abs(token["d_plus"] - token["d_minus"]), abs(token["d_plus"]))
                    for token in record["tokens"]
                ]
            )
    N = len(recs)
    if N == 0:
        raise ValueError("Token dump is empty; cannot build LookAway priors.")

    sel, occ = defaultdict(int), defaultdict(int)
    for b in range(0, N, BATCH):
        ch = recs[b : b + BATCH]
        dd = np.array([t[1] for ts in ch for t in ts])
        eps = np.array([t[2] for ts in ch for t in ts])
        s = dd / (dd + max(np.percentile(dd, 90), 0.25)) * eps / (eps + max(np.percentile(eps, 90), 0.25))
        thr = np.percentile(s, 90)
        k = 0
        for ts in ch:
            for w, d, e in ts:
                occ[w] += 1
                if s[k] > thr:
                    sel[w] += 1
                k += 1
    rate = {w: (sel[w] + ALPHA * BASE) / (occ[w] + ALPHA) for w in occ}

    bi_docs = defaultdict(set)
    for i, ts in enumerate(recs):
        for j in range(1, len(ts)):
            bi_docs[(ts[j - 1][0], ts[j][0])].add(i)
    tmpl_pairs = [bg for bg, docs in bi_docs.items() if len(docs) / N >= TMPL_DF_CUT]

    def to_id(w):
        tid = tok.convert_tokens_to_ids(w)
        return None if tid is None or tid == tok.unk_token_id else int(tid)

    rate_ids, miss = {}, 0
    for w, r in rate.items():
        tid = to_id(w)
        if tid is None:
            miss += 1
            continue
        rate_ids[tid] = round(r, 4)
    tmpl_ids = []
    for prev, cur in tmpl_pairs:
        p, c = to_id(prev), to_id(cur)
        if p is not None and c is not None:
            tmpl_ids.append([p, c])

    meta = {
        "n_samples": N,
        "model_path": args.model_path,
        "model_revision": args.model_revision or None,
        "tokenizer_name_or_path": getattr(tok, "name_or_path", None),
        "tokenizer_vocab_size": getattr(tok, "vocab_size", None),
        "tokenizer_sha256": tokenizer_fingerprint(tok),
        "chat_template": os.path.abspath(args.chat_template) if args.chat_template else None,
        "chat_template_sha256": file_sha256(args.chat_template) if args.chat_template else None,
        "generation_results_sha256": file_sha256(os.path.join(args.data_dir, "results.json")),
        "train_parquet_sha256": file_sha256(os.path.join(args.data_dir, "train.parquet")),
        "alpha": ALPHA,
        "base": BASE,
        "tmpl_df_cut": TMPL_DF_CUT,
        "rate_cut": 0.12,
        "n_rate": len(rate_ids),
        "n_tmpl": len(tmpl_ids),
        "id_miss": miss,
    }
    out = os.path.join(args.data_dir, "token_priors.json")
    temp_path = f"{out}.tmp.{os.getpid()}"
    try:
        with open(temp_path, "w", encoding="utf-8") as stream:
            json.dump({"rate": rate_ids, "tmpl": tmpl_ids, "meta": meta}, stream)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp_path, out)
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)
    print(f"Priors written: {out}")
    print("meta:", meta)


def main():
    args = parse_args()
    if os.path.exists(args.model_path):
        revision = None
    elif args.model_revision:
        revision = args.model_revision
    elif args.model_path == DEFAULT_MODEL_PATH:
        revision = DEFAULT_MODEL_REVISION
    else:
        raise ValueError("--model-revision is required for a non-default remote model")
    args.model_revision = revision
    tok = AutoTokenizer.from_pretrained(args.model_path, revision=revision, trust_remote_code=True)
    proc = AutoProcessor.from_pretrained(args.model_path, revision=revision, trust_remote_code=True)
    model = AutoModelForImageTextToText.from_pretrained(
        args.model_path,
        revision=revision,
        torch_dtype=torch.bfloat16,
        device_map=args.device,
        trust_remote_code=True,
    )
    model.eval()

    dump_path = run_dump(args, tok, proc, model)
    del model
    torch.cuda.empty_cache()
    run_priors(args, dump_path, tok)


if __name__ == "__main__":
    main()
