#!/usr/bin/env python3
"""Build the frozen LookAway token priors.

Usage:
    python scripts/prepare_priors.py --data-dir ./cache/lookaway \
        --model-path Qwen/Qwen3.5-4B [--device cuda:0] [--limit N]

Stage 1 - three-view token dump: the base model greedily answers every
training question from the student view (red-box full image); the same answer
is re-scored under the positive teacher view (official crop) and the negative
teacher view (generated by prepare_data.py). Per-token log-probabilities are
stored, together with the per-token deltas d_plus = lp_pos - lp_student and
d_minus = lp_neg - lp_student.

Stage 2 - priors derived from the dump (token-id keyed):
  * word selection rate: empirical-Bayes smoothed rate at which each token
    passes the dual-signal top-decile selection; used as an eligibility gate
    (function words score far below the 0.12 cut, content words above it);
  * template bigrams: contextual bigrams whose document frequency across the
    corpus reaches 0.25; used to reject pointing boilerplate.

Output: {data_dir}/token_priors.json  (keys: rate / tmpl / meta)
"""
import argparse
import json
import os
from collections import defaultdict

import numpy as np
import torch
from PIL import Image
from transformers import AutoTokenizer, AutoProcessor, AutoModelForImageTextToText

ALPHA, BASE = 50.0, 0.10   # empirical-Bayes pseudo-counts
BATCH = 16
TMPL_DF_CUT = 0.25
MAX_NEW_TOKENS = 96


def parse_args():
    ap = argparse.ArgumentParser(description="Build frozen LookAway token priors.")
    ap.add_argument("--data-dir", default="./cache/lookaway")
    ap.add_argument("--model-path", default="Qwen/Qwen3.5-4B")
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--limit", type=int, default=0,
                    help=">0: use only the first N samples (smoke test)")
    ap.add_argument("--chat-template", default=None,
                    help="Optional path to the training chat template (e.g. "
                         "chat_templates/perception_chat_template_qwen35.jinja); by default "
                         "the processor's own template is used")
    return ap.parse_args()


def build_inputs(proc, img_path, question, answer=None, device="cuda", chat_template=None):
    content = [{"type": "image", "image": img_path},
               {"type": "text", "text": question.replace("<image>\n", "")}]
    msgs = [{"role": "user", "content": content}]
    if answer is not None:
        msgs.append({"role": "assistant", "content": answer})
    kwargs = {}
    if chat_template is not None:
        with open(chat_template, encoding="utf-8") as f:
            kwargs["chat_template"] = f.read()
    text = proc.apply_chat_template(msgs, tokenize=False, add_generation_prompt=(answer is None),
                                    enable_thinking=False, **kwargs)
    img = Image.open(img_path).convert("RGB")
    inputs = proc(text=[text], images=[img], return_tensors="pt").to(device)
    return inputs


def run_dump(args, tok, proc, model):
    """Stage 1: three-view greedy scoring dump (rows with a failed negative
    view in prepare_data.py are skipped)."""
    out_path = os.path.join(args.data_dir, "token_scores_full.jsonl")
    rows = [json.loads(l) for l in open(os.path.join(args.data_dir, "train.jsonl"), encoding="utf-8")]
    if args.limit > 0:
        rows = rows[:args.limit]

    results_path = os.path.join(args.data_dir, "results.json")
    if os.path.exists(results_path):
        ok = {r["idx"] for r in json.load(open(results_path)) if r.get("ok")}
    else:
        ok = set(range(len(rows)))
    skipped = [i for i in range(len(rows)) if i not in ok]
    total = len(rows) - len(skipped)
    if skipped:
        print(f"Skipping {len(skipped)} rows without a negative view "
              f"(first few: {skipped[:5]}); their priors contribution is dropped.")

    tpl = args.chat_template
    fout = open(out_path, "w")
    n_written = 0
    for i, h in enumerate(rows):
        if i not in ok:
            continue
        q = h["extra_info"]["question"]

        # 1) greedy student rollout
        inputs = build_inputs(proc, os.path.join(args.data_dir, h["images"][0]), q,
                              device=args.device, chat_template=tpl)
        with torch.no_grad():
            out = model.generate(**inputs, max_new_tokens=MAX_NEW_TOKENS, do_sample=False,
                                 pad_token_id=tok.eos_token_id)
        gen_ids = out[0][inputs["input_ids"].shape[1]:]
        answer = tok.decode(gen_ids, skip_special_tokens=True).strip()
        ans_ids = tok(answer, add_special_tokens=False)["input_ids"]
        K = len(ans_ids)

        # 2) three-view scoring
        lps = {}
        views = {
            "student": os.path.join(args.data_dir, h["images"][0]),
            "pos": os.path.join(args.data_dir, h["teacher_images"][0]),
            "neg": os.path.join(args.data_dir, "teacher_neg", "%06d.png" % i),
        }
        for tag, img_path in views.items():
            inputs = build_inputs(proc, img_path, q, answer, device=args.device, chat_template=tpl)
            with torch.no_grad():
                logits = model(**inputs).logits[0]
            lp = torch.log_softmax(logits.float(), dim=-1)
            ids = inputs["input_ids"][0]
            idl = ids.tolist()
            pos_ans = None
            for st in range(len(idl) - K, max(0, len(idl) - K - 10), -1):
                if idl[st:st + K] == ans_ids:
                    pos_ans = st
                    break
            if pos_ans is None:
                pos_ans = len(idl) - K - 1
            vals = []
            for j in range(K):
                t_pos = pos_ans + j
                vals.append(lp[t_pos - 1, idl[t_pos]].item())
            lps[tag] = vals

        # 3) per-token deltas (relative to the student score)
        rec = {"n": n_written, "idx": i, "gt": h.get("answer", ""), "answer": answer,
               "question": q[:100], "tokens": []}
        toks = tok.convert_ids_to_tokens(ans_ids)
        for j, t in enumerate(toks):
            ds = lps["student"][j]
            rec["tokens"].append({
                "tok": t,
                "lp_s": round(ds, 4),
                "d_plus": round(lps["pos"][j] - ds, 4),
                "d_minus": round(lps["neg"][j] - ds, 4),
            })
        fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
        fout.flush()
        n_written += 1
        if n_written % 100 == 0:
            print(f"dump [{n_written}/{total}]", flush=True)
    fout.close()
    print(f"Token dump written: {out_path}")
    return out_path


def run_priors(args, dump_path, tok):
    """Stage 2: frozen priors from the dump."""
    recs = []
    for i, line in enumerate(open(dump_path, errors="ignore")):
        r = json.loads(line)
        recs.append([(str(t["tok"]), abs(t["d_plus"] - t["d_minus"]), abs(t["d_plus"]))
                     for t in r["tokens"]])
    N = len(recs)

    sel, occ = defaultdict(int), defaultdict(int)
    for b in range(0, N, BATCH):
        ch = recs[b:b + BATCH]
        dd = np.array([t[1] for ts in ch for t in ts])
        eps = np.array([t[2] for ts in ch for t in ts])
        s = dd / (dd + max(np.percentile(dd, 90), 0.25)) * eps / (eps + max(np.percentile(eps, 90), 0.25))
        thr = np.percentile(s, 90)
        k = 0
        for ts in ch:
            for w, d, e in ts:
                occ[w] += 1
                if s[k] > thr:
                    sel[w] += 1
                k += 1
    rate = {w: (sel[w] + ALPHA * BASE) / (occ[w] + ALPHA) for w in occ}

    bi_docs = defaultdict(set)
    for i, ts in enumerate(recs):
        for j in range(1, len(ts)):
            bi_docs[(ts[j - 1][0], ts[j][0])].add(i)
    tmpl_pairs = [bg for bg, docs in bi_docs.items() if len(docs) / N >= TMPL_DF_CUT]

    def to_id(w):
        tid = tok.convert_tokens_to_ids(w)
        return None if tid is None or tid == tok.unk_token_id else int(tid)

    rate_ids, miss = {}, 0
    for w, r in rate.items():
        tid = to_id(w)
        if tid is None:
            miss += 1
            continue
        rate_ids[tid] = round(r, 4)
    tmpl_ids = []
    for prev, cur in tmpl_pairs:
        p, c = to_id(prev), to_id(cur)
        if p is not None and c is not None:
            tmpl_ids.append([p, c])

    meta = {"n_samples": N, "alpha": ALPHA, "base": BASE, "tmpl_df_cut": TMPL_DF_CUT,
            "rate_cut": 0.12, "n_rate": len(rate_ids), "n_tmpl": len(tmpl_ids), "id_miss": miss}
    out = os.path.join(args.data_dir, "token_priors.json")
    json.dump({"rate": rate_ids, "tmpl": tmpl_ids, "meta": meta}, open(out, "w"))
    print(f"Priors written: {out}")
    print("meta:", meta)


def main():
    args = parse_args()
    tok = AutoTokenizer.from_pretrained(args.model_path, trust_remote_code=True)
    proc = AutoProcessor.from_pretrained(args.model_path, trust_remote_code=True)
    model = AutoModelForImageTextToText.from_pretrained(
        args.model_path, torch_dtype=torch.bfloat16, device_map=args.device,
        trust_remote_code=True)
    model.eval()

    dump_path = run_dump(args, tok, proc, model)
    del model
    torch.cuda.empty_cache()
    run_priors(args, dump_path, tok)


if __name__ == "__main__":
    main()
